### ISSUE TITLE
JEC and JER up and down

### ISSUE THREAD

**Issue by nhanvtran** [DAZSLE/BaconAnalyzer#11]
Access this information in the BaconProd and put into the Bacon Bits

**Comment by nhanvtran** [comment]
Need both AK4 and AK8

**Comment by jmduarte** [comment]
#14 is the first iteration.
Things still missing are:
propagating this to the ak4 njets (which we use for the selection)
propagating this to the MET (which we use for the selection)
reading in the text file to get the correct sigma_MC (needed for JER smearing centra/Up/Down)
